WITH LISTINGS AS(
	SELECT * FROM {{ ref('dim_listings_cleaned') }}
),
HOSTS AS(
	SELECT * FROM {{ ref('dim_hosts_cleaned') }}
)

SELECT 
	L.LISTING_ID,
	L.LISTING_NAME,
	L.ROOM_TYPE,
	L.MINIMUM_NIGHTS,
	L.PRICE,
	L.HOST_ID,
	H.HOST_NAME,
	H.IS_SUPERHOST AS HOST_IS_SUPERHOST,
	L.CREATED_AT,
	GREATEST(L.UPDATED_AT, H.UPDATED_AT) AS UPDATED_AT
FROM LISTINGS L LEFT JOIN HOSTS H ON L.HOST_ID = H.HOST_ID

