models:
  - name: dim_listings_cleaned
    data_tests:
      - minimum_row_count:
          arguments:
            min_row_count: 10000000000
          severity: warn

    columns:
      - name: listing_id
        description: primary key for listings table
        data_tests:
          - unique
          - not_null

      - name: host_id
        description: primary key for hosts table
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_hosts_cleaned')
                field: host_id

      - name: room_type
        description: categories of room needed
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Shared room', 'Private room',  'Hotel room', 'Entire home/apt']

      - name: minimum_nights
        description: '{{ doc("minimum_nights_docs") }}'
        data_tests:
          - positive_values


  - name: dim_hosts_cleaned
    config:
      contract:
        enforced: true
    columns:
      - name: host_id
        description: primary key for host table
        data_type: integer
      - name: host_name
        description: name of the host
        data_type: string
      - name: is_superhost
        description: whether hosts in given row is a a superhost?
        data_type: string
      - name: updated_at
        description: when row was updated
        data_type: timestamp
      - name: created_at
        description: when row was created
        data_type: timestamp
