models:
  - name: dim_listings_cleaned
    data_tests:
      - minimum_row_count:
          arguments:
            min_row_count: 10000000000
          severity: warn

    columns:
      - name: listing_id
        data_tests:
          - unique
          - not_null

      - name: host_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_hosts_cleaned')
                field: host_id

      - name: room_type
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Shared room', 'Private room',  'Hotel room', 'Entire home/apt']

      - name: minimum_nights
        data_tests:
          - positive_values


  - name: dim_hosts_cleaned
    config:
      contract:
        enforced: true
    columns:
      - name: host_id
        data_type: integer
      - name: host_name
        data_type: string
      - name: is_superhost
        data_type: string
      - name: updated_at
        data_type: timestamp
      - name: created_at
        data_type: timestamp
